name: CI for BobApp2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test-front-end:
    name: Build and Test Front-end
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'

    - name: Install packages
      run: npm ci
      working-directory: ./front

    - name: Build package
      run: npm run build --if-present
      working-directory: ./front

    - name: Run Test
      run: npm test -- --watch=false --browsers=ChromeHeadless
      working-directory: ./front

    - name: Build front-end container
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-front:latest .
      working-directory: ./front

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push front-end container
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-front:latest
      working-directory: ./front

  build-and-test-back-end:
    name: Build and Test Back-end
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Install back-end dependencies
      run: mvn clean install
      working-directory: ./back

    - name: Launch Test with Maven
      run: mvn clean test
      working-directory: ./back

    - name: Build back-end container
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-back:latest .
      working-directory: ./back

    - name: Log in to Docker Hub (if not logged in already)
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push back-end container
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-back:latest
      working-directory: ./back

  sonarcloud-analysis:
    name: SonarCloud Analysis
    needs: [build-and-test-front-end, build-and-test-back-end]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up SonarCloud scanner
      uses: SonarSource/sonarcloud-github-action@v1.6
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=sabriderbala_collaborativ_project_ci_cd
          -Dsonar.organization=sabriderbala
          -Dsonar.sources=front,back
          -Dsonar.tests=front,back
          -Dsonar.test.inclusions=**/*.spec.ts,**/*.test.ts,**/*.spec.js,**/*.test.js
          -Dsonar.javascript.lcov.reportPaths=front/coverage/lcov.info
          -Dsonar.java.coveragePlugin=jacoco
          -Dsonar.jacoco.reportPaths=back/target/jacoco.exec
          -Dsonar.java.source=11 # Spécifiez la version 11 de Java ici
